"""Interface text in English and Portuguese (the language of the Coimbra partner).

Copy is deliberately jargon-free; scientific terms are explained on first use.
Falls back to English for any missing key. The insight texts themselves (titles,
findings, challenge details) are generated by the engine in English.
"""
from __future__ import annotations

LANGS = {"en": "English", "pt": "Português"}

_STR = {
    # ---- navigation
    "nav": {"en": "View", "pt": "Vista"},
    "nav_page": {"en": "Page", "pt": "Página"},
    "mode_main": {"en": "Insights", "pt": "Descobertas"},
    "mode_tools": {"en": "Tools", "pt": "Ferramentas"},
    "insight_feed": {"en": "Insight feed", "pt": "Descobertas"},
    "watchlist": {"en": "Priority lens", "pt": "Lente de prioridades"},
    "fingerprints": {"en": "Observed risk profiles", "pt": "Perfis de risco observados"},
    "map": {"en": "Risk map", "pt": "Mapa de risco"},
    "health_card": {"en": "Site health card", "pt": "Ficha do local"},
    "citizen": {"en": "Citizen site check", "pt": "Verificação de local"},
    "quality": {"en": "Citizen data quality", "pt": "Qualidade dos dados"},
    "drivers": {"en": "Landscape & model", "pt": "Paisagem e modelo"},
    "about": {"en": "About & export", "pt": "Sobre e exportação"},
    "disclaimer": {
        "en": "Screening and prioritisation only. Not a diagnosis and not a 'safe to swim' judgement.",
        "pt": "Apenas triagem e priorização. Não é um diagnóstico nem uma indicação de 'seguro para nadar'.",
    },
    # ---- shared vocabulary
    "c_pathogen": {"en": "Pathogen risk", "pt": "Risco de patógenos"},
    "c_faecal": {"en": "Faecal risk", "pt": "Risco fecal"},
    "c_arg": {"en": "Antibiotic-resistance (ARG) risk", "pt": "Risco de resistência a antibióticos (ARG)"},
    "c_composite": {"en": "Composite score", "pt": "Índice composto"},
    "c_nitrate": {"en": "Nitrate", "pt": "Nitrato"},
    "band_unknown": {"en": "no measurement", "pt": "sem medição"},
    "band_low": {"en": "low", "pt": "baixo"},
    "band_lowmod": {"en": "low to moderate", "pt": "baixo a moderado"},
    "band_mod": {"en": "moderate", "pt": "moderado"},
    "band_elev": {"en": "elevated", "pt": "elevado"},
    "band_high": {"en": "high", "pt": "alto"},
    "site": {"en": "Site", "pt": "Local"},
    "site_name": {"en": "Site name", "pt": "Nome do local"},
    "city": {"en": "City", "pt": "Cidade"},
    "all_cities": {"en": "All cities", "pt": "Todas as cidades"},
    "sites": {"en": "Monitoring sites", "pt": "Locais monitorizados"},
    "sites_lc": {"en": "sites", "pt": "locais"},
    "with_labs": {"en": "Sites with lab results", "pt": "Locais com resultados de laboratório"},
    "yes": {"en": "yes", "pt": "sim"},
    "no": {"en": "no", "pt": "não"},
    "eg": {"en": "Highest:", "pt": "Mais altos:"},
    "latitude": {"en": "Latitude", "pt": "Latitude"},
    "longitude": {"en": "Longitude", "pt": "Longitude"},
    "feature": {"en": "Feature", "pt": "Variável"},
    "positive": {"en": "positive", "pt": "positiva"},
    "negative": {"en": "negative", "pt": "negativa"},
    "uncorrected": {"en": "uncorrected", "pt": "sem correção"},
    "flagged": {"en": "sites flagged", "pt": "locais sinalizados"},
    # ---- verdicts & evidence card
    "st_supported": {"en": "Supported", "pt": "Sustentado"},
    "st_exploratory": {"en": "Exploratory", "pt": "Exploratório"},
    "st_rejected": {"en": "Rejected", "pt": "Rejeitado"},
    "evidence_lbl": {"en": "Evidence", "pt": "Evidência"},
    "limitation_lbl": {"en": "What we cannot conclude", "pt": "O que não podemos concluir"},
    "next_lbl": {"en": "Suggested next step", "pt": "Próximo passo sugerido"},
    "challenge_lbl": {"en": "How this was challenged", "pt": "Como foi posto à prova"},
    "dim_observed": {"en": "Observed", "pt": "Observado"},
    "dim_association": {"en": "Association", "pt": "Associação"},
    "dim_prediction": {"en": "Prediction", "pt": "Previsão"},
    "dim_causal": {"en": "Causal", "pt": "Causal"},
    # ---- insight feed
    "feed_title": {"en": "What does the data actually support?",
                   "pt": "O que é que os dados realmente sustentam?"},
    "feed_intro": {
        "en": "AquaSentinel searched the OneAquaHealth network for patterns, then tried to "
              "disprove each one. Every finding below carries its evidence and a verdict.",
        "pt": "O AquaSentinel procurou padrões na rede OneAquaHealth e depois tentou refutar "
              "cada um. Cada descoberta abaixo traz a sua evidência e um veredicto.",
    },
    "headline_lbl": {"en": "HEADLINE FINDING · SUPPORTED", "pt": "DESCOBERTA PRINCIPAL · SUSTENTADA"},
    "headline_title": {
        "en": "ARG risk behaves differently from faecal risk — and a composite score can miss high-ARG sites",
        "pt": "O risco ARG comporta-se de forma diferente do risco fecal — e um índice composto pode falhar locais com ARG alto",
    },
    "headline_body": {
        "en": "Pathogen and faecal risk rise and fall together. Antibiotic-resistance (ARG) risk "
              "shows no detectable association with faecal risk. So the composite top quarter "
              "leaves out **{missed} of the {top} highest-ARG sites** in the network.",
        "pt": "O risco de patógenos e o risco fecal sobem e descem juntos. O risco de resistência "
              "a antibióticos (ARG) não mostra associação detetável com o risco fecal. Por isso, o "
              "quarto superior do índice composto deixa de fora **{missed} dos {top} locais com ARG mais alto**.",
    },
    "chart_pf": {"en": "Pathogen follows faecal (rho = {r})", "pt": "Patógenos acompanham o fecal (rho = {r})"},
    "chart_fa": {"en": "ARG shows no detectable link (rho = {r})", "pt": "O ARG não mostra ligação detetável (rho = {r})"},
    "headline_caption": {
        "en": "Each dot is one site (n = {n}); hover for details. Faecal-vs-ARG 95% confidence "
              "interval: {lo} to {hi}, which spans zero.",
        "pt": "Cada ponto é um local (n = {n}); passe o cursor para ver detalhes. Intervalo de "
              "confiança a 95% para fecal-vs-ARG: {lo} a {hi}, que inclui zero.",
    },
    "all_insights": {"en": "All insights", "pt": "Todas as descobertas"},
    "verdict_help": {
        "en": "Supported = survived every challenge that applies; the strongest verdict this "
              "data allows, not proof. Exploratory = survived the city check but "
              "not the correction for testing many features; a hypothesis, not a finding. "
              "Rejected = failed the challenge.",
        "pt": "Sustentado = resistiu a todos os testes aplicáveis; o veredicto mais forte que "
              "estes dados permitem, não uma prova. Exploratório = resistiu ao teste por "
              "cidade mas não à correção por testar muitas variáveis; é uma hipótese. "
              "Rejeitado = não resistiu ao teste.",
    },
    "filter_verdict": {"en": "Show", "pt": "Mostrar"},
    # ---- watchlist
    "watch_title": {"en": "Which sites should be looked at first?",
                    "pt": "Que locais devem ser vistos primeiro?"},
    "watch_intro": {
        "en": "The top quarter of sites on the dimension you choose, from **observed lab "
              "values only**. Switch the dimension to see how the list changes — that is the "
              "headline finding in practice.",
        "pt": "O quarto superior dos locais na dimensão escolhida, **apenas com valores de "
              "laboratório observados**. Mude a dimensão para ver como a lista se altera — é a "
              "descoberta principal na prática.",
    },
    "rank_by": {"en": "Rank by", "pt": "Ordenar por"},
    "watch_n": {"en": "Sites on this list", "pt": "Locais nesta lista"},
    "watch_n_help": {"en": "Top quarter of the sites with lab results.",
                     "pt": "Quarto superior dos locais com resultados de laboratório."},
    "watch_missed": {"en": "Not on the composite list", "pt": "Fora da lista do índice composto"},
    "watch_missed_help": {
        "en": "Sites in the top quarter for this dimension that the composite score would not flag.",
        "pt": "Locais no quarto superior nesta dimensão que o índice composto não sinalizaria.",
    },
    "watch_hot": {"en": "Also a hotspot in their city", "pt": "Também ponto crítico na sua cidade"},
    "watch_hot_help": {
        "en": "At least 1.5 standard deviations above their own city's mean composite score.",
        "pt": "Pelo menos 1,5 desvios-padrão acima da média do índice composto da cidade.",
    },
    "col_on_composite": {"en": "On composite list", "pt": "Na lista do composto"},
    "col_hotspot": {"en": "City hotspot", "pt": "Ponto crítico"},
    "col_sampled": {"en": "Sampled", "pt": "Amostrado"},
    "download_watch": {"en": "Download this list (CSV)", "pt": "Descarregar esta lista (CSV)"},
    "watch_honesty": {
        "en": "One sample per site, taken between May and September 2023. Use this to decide "
              "where to sample again, not to declare a site safe or unsafe.",
        "pt": "Uma amostra por local, recolhida entre maio e setembro de 2023. Use isto para "
              "decidir onde voltar a amostrar, não para declarar um local seguro ou inseguro.",
    },
    # ---- contamination profiles
    "fp_title": {"en": "Observed risk profiles", "pt": "Perfis de risco observados"},
    "fp_intro": {
        "en": "Sites grouped by their observed pathogen, faecal and ARG values. The groups "
              "separate on pathogen and faecal contamination; ARG is spread across both.",
        "pt": "Locais agrupados pelos valores observados de patógenos, fecal e ARG. Os grupos "
              "separam-se pela contaminação por patógenos e fecal; o ARG distribui-se por ambos.",
    },
    "profile": {"en": "Profile", "pt": "Perfil"},
    "fp_chart_sep": {"en": "The profiles separate on pathogen and faecal risk",
                     "pt": "Os perfis separam-se no risco de patógenos e fecal"},
    "fp_chart_arg": {"en": "…but both profiles span the full range of ARG risk",
                     "pt": "…mas ambos cobrem toda a gama de risco ARG"},
    # ---- map
    "map_title": {"en": "Where is each kind of risk concentrated?",
                  "pt": "Onde se concentra cada tipo de risco?"},
    "layer": {"en": "Colour sites by", "pt": "Colorir os locais por"},
    "zoom_to": {"en": "Zoom to", "pt": "Aproximar de"},
    "show_citizen": {"en": "Show citizen-registered sites", "pt": "Mostrar locais registados por cidadãos"},
    "citizen_site": {"en": "Citizen site", "pt": "Local de cidadão"},
    "map_caption": {
        "en": "{n} of {total} sites have a value for this layer. Darker = higher. Observed lab "
              "values; hollow grey rings are cleaned citizen registrations.",
        "pt": "{n} de {total} locais têm valor nesta camada. Mais escuro = mais alto. Valores "
              "de laboratório observados; os anéis cinzentos são registos de cidadãos já limpos.",
    },
    # ---- health card
    "card_title": {"en": "Site health card", "pt": "Ficha de saúde do local"},
    "select_site": {"en": "Choose a site", "pt": "Escolha um local"},
    "sampled_on": {"en": "Lab sample taken on {d}.", "pt": "Amostra de laboratório recolhida em {d}."},
    "card_hidden": {
        "en": "The composite score understates this site. Its **{dim}** is higher than {pd}% of "
              "all sites, while its composite score is higher than only {pc}%.",
        "pt": "O índice composto subestima este local. O seu **{dim}** é superior a {pd}% de "
              "todos os locais, enquanto o índice composto é superior a apenas {pc}%.",
    },
    "percentile_line": {
        "en": "Composite score higher than **{pc}%** of sites in {city} and **{pe}%** across all five cities.",
        "pt": "Índice composto superior a **{pc}%** dos locais em {city} e **{pe}%** nas cinco cidades.",
    },
    "nitrate_line": {
        "en": "Nitrate: **{v} mg/L**. For context only: the EU drinking-water limit is 50 mg/L as "
              "nitrate ({ref} mg/L as nitrate-nitrogen); it is not a standard for streams.",
        "pt": "Nitrato: **{v} mg/L**. Apenas como contexto: o limite da UE para água de consumo é "
              "50 mg/L em nitrato ({ref} mg/L em azoto nítrico); não é uma norma para ribeiras.",
    },
    "card_context": {"en": "Landscape context (exploratory)", "pt": "Contexto da paisagem (exploratório)"},
    "card_context_note": {
        "en": "What a model fitted on all five cities associates with this site's values. The "
              "model does not predict risk in an unseen city, so read these as hypotheses.",
        "pt": "O que um modelo ajustado às cinco cidades associa aos valores deste local. O modelo "
              "não prevê o risco numa cidade nova; leia isto como hipóteses.",
    },
    "no_drivers": {"en": "The model finds no landscape factor that stands out here.",
                   "pt": "O modelo não encontra nenhum fator da paisagem que se destaque aqui."},
    "card_honesty": {
        "en": "All numbers above are observed lab values on a 0 to 1 relative scale defined by "
              "OneAquaHealth. They rank sites against each other; they are not probabilities of harm.",
        "pt": "Todos os números acima são valores de laboratório observados numa escala relativa "
              "de 0 a 1 definida pelo OneAquaHealth. Ordenam os locais entre si; não são "
              "probabilidades de dano.",
    },
    # ---- landscape & model
    "drivers_title": {"en": "Can landscape data predict stream health risk?",
                      "pt": "Os dados da paisagem conseguem prever o risco?"},
    "drivers_intro": {
        "en": "Short answer: not in a city the model has not seen. This page shows the test.",
        "pt": "Resposta curta: não numa cidade que o modelo não viu. Esta página mostra o teste.",
    },
    "validation": {"en": "Train on four cities, test on the fifth",
                   "pt": "Treinar em quatro cidades, testar na quinta"},
    "col_target": {"en": "Target", "pt": "Alvo"},
    "col_model_err": {"en": "Model error", "pt": "Erro do modelo"},
    "col_base_err": {"en": "Baseline error", "pt": "Erro da referência"},
    "col_beats": {"en": "Beats baseline?", "pt": "Supera a referência?"},
    "col_city_rank": {"en": "Rank agreement inside the held-out city",
                      "pt": "Concordância de ordenação na cidade excluída"},
    "validation_note": {
        "en": "Error = mean absolute error on the 0 to 1 scale. Baseline = predict the mean of "
              "the four training cities. Rank agreement = Spearman correlation between "
              "predicted and observed values inside each held-out city, averaged over cities.",
        "pt": "Erro = erro absoluto médio na escala de 0 a 1. Referência = prever a média das "
              "quatro cidades de treino. Concordância = correlação de Spearman entre valores "
              "previstos e observados em cada cidade excluída, em média.",
    },
    "model_honesty": {
        "en": "The model does not beat the baseline for any target, with elastic-net or with "
              "gradient boosting. So AquaSentinel does not forecast risk and does not rank "
              "unsampled sites. Landscape appears only as exploratory context.",
        "pt": "O modelo não supera a referência em nenhum alvo, nem com elastic-net nem com "
              "gradient boosting. Por isso o AquaSentinel não prevê o risco nem ordena locais "
              "não amostrados. A paisagem aparece apenas como contexto exploratório.",
    },
    "associations": {"en": "Strongest raw associations with the composite score",
                     "pt": "Associações brutas mais fortes com o índice composto"},
    "associations_note": {
        "en": "Before any challenge. The insight feed shows which of these survive the city "
              "check and the correction for screening 59 features (none is supported).",
        "pt": "Antes de qualquer teste. As descobertas mostram quais resistem ao teste por cidade "
              "e à correção por analisar 59 variáveis (nenhuma é sustentada).",
    },
    # ---- citizen site check
    "citizen_title": {"en": "Check a site before it is registered",
                      "pt": "Verificar um local antes de o registar"},
    "citizen_intro": {
        "en": "The checks a citizen-science app should run at the moment of entry: are the "
              "coordinates plausible, is this place already registered, and is there lab data nearby?",
        "pt": "As verificações que uma aplicação de ciência cidadã deve fazer no momento do "
              "registo: as coordenadas são plausíveis, o local já existe, há dados de laboratório perto?",
    },
    "check_btn": {"en": "Check this site", "pt": "Verificar este local"},
    "citizen_try": {
        "en": "Try the default: a real entry from the citizen data whose latitude and longitude "
              "are swapped. Then try 50.81345, 3.77993 — a place already registered six times.",
        "pt": "Experimente o exemplo: um registo real dos dados dos cidadãos com latitude e "
              "longitude trocadas. Depois experimente 50.81345, 3.77993 — um local já registado seis vezes.",
    },
    "step1": {"en": "1. Is the entry sound?", "pt": "1. O registo está correto?"},
    "f_invalid": {"en": "These coordinates are not on Earth: latitude must be between −90 and 90, "
                        "longitude between −180 and 180.",
                  "pt": "Estas coordenadas não existem: a latitude deve estar entre −90 e 90 e a "
                        "longitude entre −180 e 180."},
    "f_swapped": {"en": "Latitude and longitude look swapped. Did you mean latitude {lat}, "
                        "longitude {lon}? The checks below use the corrected position.",
                  "pt": "A latitude e a longitude parecem trocadas. Queria dizer latitude {lat}, "
                        "longitude {lon}? As verificações abaixo usam a posição corrigida."},
    "f_junk": {"en": "The name looks like a test or placeholder. A real name helps others find the site.",
               "pt": "O nome parece um teste ou provisório. Um nome real ajuda outros a encontrar o local."},
    "f_duplicate": {"en": "This place is already registered as “{name}” ({m} m away).",
                    "pt": "Este local já está registado como “{name}” (a {m} m)."},
    "f_ok": {"en": "Coordinates and name look sound, and this is a new place.",
             "pt": "As coordenadas e o nome parecem corretos e é um local novo."},
    "step2": {"en": "2. Is there lab data nearby?", "pt": "2. Há dados de laboratório perto?"},
    "near_site": {"en": "Nearest lab-monitored site: **{code} — {name}** ({city}), {km} km away. Its lab results:",
                  "pt": "Local monitorizado mais próximo: **{code} — {name}** ({city}), a {km} km. Resultados:"},
    "near_caveat": {
        "en": "Measured at that site on {d}. It tells you what was found nearby, not what is in "
              "your stream today.",
        "pt": "Medido nesse local em {d}. Indica o que foi encontrado perto, não o que está na "
              "sua ribeira hoje.",
    },
    "near_nolab": {"en": "That site has no lab results yet.", "pt": "Esse local ainda não tem resultados."},
    "in_city": {"en": "Inside the {city} study area, but the nearest lab-monitored site is {km} km "
                      "away — too far to say anything about this stream.",
                "pt": "Dentro da área de estudo de {city}, mas o local monitorizado mais próximo "
                      "fica a {km} km — demasiado longe para dizer algo sobre esta ribeira."},
    "new_coverage": {"en": "No lab-monitored site within reach (nearest is {km} km away). This "
                           "registration adds a stream the network does not yet cover.",
                     "pt": "Nenhum local monitorizado ao alcance (o mais próximo fica a {km} km). "
                           "Este registo acrescenta uma ribeira que a rede ainda não cobre."},
    "step3": {"en": "3. What to do next", "pt": "3. O que fazer a seguir"},
    "a_fix_coords": {"en": "Confirm the corrected coordinates before saving.",
                     "pt": "Confirme as coordenadas corrigidas antes de guardar."},
    "a_add_visit": {"en": "Add your observation as a new visit to “{name}” instead of creating a new site.",
                    "pt": "Adicione a sua observação como nova visita a “{name}” em vez de criar um local novo."},
    "a_rename": {"en": "Give the site a real name, such as the stream and the nearest street or bridge.",
                 "pt": "Dê um nome real ao local, como a ribeira e a rua ou ponte mais próxima."},
    "a_avoid": {"en": "The nearby lab result was moderate or higher on at least one dimension: "
                      "avoid direct contact with the water, especially after heavy rain.",
                "pt": "O resultado de laboratório próximo foi moderado ou superior em pelo menos uma "
                      "dimensão: evite o contacto direto com a água, sobretudo após chuva forte."},
    "a_photo": {"en": "Take a photo and note colour, smell and flow; repeat in two weeks.",
                "pt": "Tire uma fotografia e registe cor, cheiro e caudal; repita dentro de duas semanas."},
    "a_report": {"en": "Report anything unusual (foam, dead fish, sewage smell) to your municipality.",
                 "pt": "Comunique ao município qualquer situação anormal (espuma, peixes mortos, cheiro a esgoto)."},
    "citizen_guardrail": {
        "en": "Every statement above comes from a rule or an observed lab value. Nothing is "
              "estimated or generated for a stream that has not been sampled.",
        "pt": "Cada afirmação acima vem de uma regra ou de um valor de laboratório observado. Nada "
              "é estimado ou gerado para uma ribeira que não foi amostrada.",
    },
    # ---- data quality
    "quality_title": {"en": "Citizen site registrations: what needs fixing",
                      "pt": "Registos de locais por cidadãos: o que é preciso corrigir"},
    "quality_intro": {
        "en": "Deterministic, explainable rules run over the real citizen registrations. Each "
              "flag comes with its suggested fix, and the cleaned registry can be downloaded.",
        "pt": "Regras determinísticas e explicáveis aplicadas aos registos reais dos cidadãos. "
              "Cada sinalização traz a correção sugerida e o registo limpo pode ser descarregado.",
    },
    "q_total": {"en": "Registrations", "pt": "Registos"},
    "q_review": {"en": "Need fixing", "pt": "A corrigir"},
    "q_junk": {"en": "Test names", "pt": "Nomes de teste"},
    "q_swapped": {"en": "Swapped coordinates", "pt": "Coordenadas trocadas"},
    "q_dup": {"en": "Duplicate entries", "pt": "Registos duplicados"},
    "q_dup_help": {"en": "They are really {n} places, each registered several times.",
                   "pt": "São na realidade {n} locais, cada um registado várias vezes."},
    "q_clean": {"en": "Usable after fixes", "pt": "Utilizáveis após correção"},
    "q_clean_help": {"en": "Test entries dropped, swaps corrected, duplicates merged.",
                     "pt": "Testes removidos, trocas corrigidas, duplicados fundidos."},
    "q_outside": {
        "en": "{n} of the {total} usable sites are more than 50 km from any lab-monitored site "
              "(Greece, Austria, Brazil, the United States and elsewhere). That is noted, not "
              "flagged: citizen science is global, and these show where the network could grow.",
        "pt": "{n} dos {total} locais utilizáveis ficam a mais de 50 km de qualquer local "
              "monitorizado (Grécia, Áustria, Brasil, Estados Unidos e outros). Isto é uma nota, "
              "não um erro: a ciência cidadã é global e estes mostram onde a rede pode crescer.",
    },
    "show_flagged": {"en": "Show only entries that need fixing", "pt": "Mostrar só os registos a corrigir"},
    "col_flags": {"en": "Flags", "pt": "Sinalizações"},
    "col_fix": {"en": "Suggested fix", "pt": "Correção sugerida"},
    "col_notes": {"en": "Notes", "pt": "Notas"},
    "fix_swap": {"en": "swap to {lat}, {lon}", "pt": "trocar para {lat}, {lon}"},
    "fix_merge": {"en": "merge into “{name}” ({n} entries)", "pt": "fundir em “{name}” ({n} registos)"},
    "fix_junk": {"en": "remove or rename", "pt": "remover ou renomear"},
    "download_clean": {"en": "Download the cleaned registry ({n} sites, CSV)",
                       "pt": "Descarregar o registo limpo ({n} locais, CSV)"},
    "rules_title": {"en": "The rules", "pt": "As regras"},
    "rules_body": {
        "en": "- **Test name**: contains “test” or “random”, is empty, or is a short string with no vowels.\n"
              "- **Swapped coordinates**: the point is more than {far} km from every known site, but "
              "swapping latitude and longitude puts it within {near} km of one; or it falls outside "
              "the partner countries and inside one when swapped.\n"
              "- **Duplicate**: within {dup} m of another registration.\n"
              "- **Outside coverage** (a note, not an error): more than {cov} km from any lab-monitored site.",
        "pt": "- **Nome de teste**: contém “test” ou “random”, está vazio ou é uma sequência curta sem vogais.\n"
              "- **Coordenadas trocadas**: o ponto fica a mais de {far} km de qualquer local conhecido, mas "
              "ao trocar latitude e longitude fica a menos de {near} km de um; ou fica fora dos países "
              "parceiros e dentro de um quando trocado.\n"
              "- **Duplicado**: a menos de {dup} m de outro registo.\n"
              "- **Fora da cobertura** (nota, não erro): a mais de {cov} km de qualquer local monitorizado.",
    },
    # ---- next campaign
    "plan": {"en": "Evidence gap", "pt": "Lacunas de evidência"},
    "plan_title": {"en": "Evidence gap: what to measure next", "pt": "Lacunas de evidência: o que medir a seguir"},
    "plan_intro": {
        "en": "A verdict is only as good as the data behind it. This page turns the insights "
              "into the next sampling campaign: which sites to visit again, and how many sites "
              "it would take before an exploratory signal could be supported or the headline "
              "made sharper.",
        "pt": "Um veredicto vale o que valem os dados por trás dele. Esta página transforma as "
              "descobertas na próxima campanha de amostragem: que locais revisitar e quantos "
              "locais seriam precisos para confirmar um sinal exploratório ou tornar a "
              "conclusão principal mais precisa.",
    },
    "plan_sites": {"en": "Sites to re-sample", "pt": "Locais a reamostrar"},
    "plan_sites_help": {
        "en": "Every site that one or more insights point at, counted once.",
        "pt": "Todos os locais indicados por uma ou mais descobertas, contados uma vez.",
    },
    "plan_multi": {"en": "Test two insights at once", "pt": "Testam duas descobertas"},
    "plan_cities": {"en": "Cities", "pt": "Cidades"},
    "plan_share": {"en": "Share of monitored sites", "pt": "Parte dos locais monitorizados"},
    "plan_list": {"en": "Sites to visit again", "pt": "Locais a revisitar"},
    "plan_list_note": {
        "en": "Sites that test more insights come first. Re-sampling in the same month checks "
              "whether the first result repeats; sampling in another season starts to separate "
              "city from season.",
        "pt": "Os locais que testam mais descobertas aparecem primeiro. Reamostrar no mesmo mês "
              "verifica se o primeiro resultado se repete; amostrar noutra estação começa a "
              "separar cidade e estação.",
    },
    "col_reasons": {"en": "Why", "pt": "Porquê"},
    "col_tests": {"en": "Insights tested", "pt": "Descobertas testadas"},
    "download_plan": {"en": "Download the campaign plan (CSV)",
                      "pt": "Descarregar o plano da campanha (CSV)"},
    "plan_gaps": {"en": "How much data would change each verdict",
                  "pt": "Quantos dados mudariam cada veredicto"},
    "plan_gaps_note": {
        "en": "Sites needed: the network size at which the effect seen today would clear the "
              "same test with 80% power (Fisher z with the Spearman variance factor 1.06). For "
              "the headline: the size at which the 95% interval shrinks to ±0.10. These are "
              "planning estimates, not guarantees.",
        "pt": "Locais necessários: o tamanho da rede com que o efeito visto hoje passaria o mesmo "
              "teste com 80% de potência (Fisher z com o fator de variância de Spearman 1,06). "
              "Para a conclusão principal: o tamanho com que o intervalo de 95% fica em ±0,10. "
              "São estimativas de planeamento, não garantias.",
    },
    "col_now": {"en": "Today", "pt": "Hoje"},
    "col_change": {"en": "What would change it", "pt": "O que o mudaria"},
    "col_needed": {"en": "Sites needed", "pt": "Locais necessários"},
    "col_verdict": {"en": "Verdict", "pt": "Veredicto"},
    "col_insight": {"en": "Insight", "pt": "Descoberta"},
    "needs_design": {"en": "new design", "pt": "novo desenho"},
    "closed": {"en": "closed", "pt": "encerrado"},
    "plan_chart": {"en": "Sites needed against the 96 monitored today (log scale)",
                   "pt": "Locais necessários face aos 96 monitorizados hoje (escala log)"},
    # ---- evidence loop (feed summary, grouping, per-card gap)
    "principle": {
        "en": "No sample, no risk score. Weak evidence is labelled exploratory; evidence that "
              "fails a challenge is rejected.",
        "pt": "Sem amostra, sem índice de risco. Evidência fraca é exploratória; evidência que "
              "falha um teste é rejeitada.",
    },
    "tested_line": {
        "en": "**{n} candidate insights tested** → {s} supported · {e} exploratory · {r} rejected",
        "pt": "**{n} descobertas candidatas testadas** → {s} sustentadas · {e} exploratórias · {r} rejeitadas",
    },
    "false_leads": {"en": "False leads stopped", "pt": "Pistas falsas travadas"},
    "false_leads_help": {
        "en": "{r} patterns rejected because they vanished inside cities, plus {d} downgraded to "
              "exploratory because they did not survive the correction for screening {f} features.",
        "pt": "{r} padrões rejeitados porque desaparecem dentro das cidades, mais {d} rebaixados "
              "a exploratórios por não resistirem à correção por analisar {f} variáveis.",
    },
    "grp_supported": {"en": "Supported findings", "pt": "Descobertas sustentadas"},
    "grp_exploratory": {"en": "Exploratory: hypotheses to test next",
                        "pt": "Exploratórias: hipóteses a testar"},
    "grp_rejected": {"en": "False leads stopped before they reached a decision",
                     "pt": "Pistas falsas travadas antes de chegarem a uma decisão"},
    "grp_rejected_note": {
        "en": "Each of these looked like a risk signal across all sites. Inside cities it "
              "disappeared, so it reflected differences between cities, not between sites.",
        "pt": "Cada uma parecia um sinal de risco em todos os locais. Dentro das cidades "
              "desapareceu: refletia diferenças entre cidades, não entre locais.",
    },
    "change_lbl": {"en": "What would change our mind", "pt": "O que nos faria mudar de ideia"},
    "sites_needed_fmt": {"en": "about {n:,} sites (today: {now})",
                         "pt": "cerca de {n:,} locais (hoje: {now})"},
    "rank_chart": {
        "en": "Composite rank against ARG rank: {missed} of the top {k} ARG sites fall outside the composite top {k}",
        "pt": "Posição no índice composto face ao ARG: {missed} dos {k} locais com ARG mais alto ficam fora do top {k} composto",
    },
    "rank_comp": {"en": "Rank on composite score (1 = highest)", "pt": "Posição no índice composto (1 = mais alto)"},
    "rank_arg": {"en": "Rank on ARG (1 = highest)", "pt": "Posição no ARG (1 = mais alto)"},
    "rank_missed": {"en": "Top-{k} ARG, missed by composite", "pt": "Top {k} ARG, falhado pelo composto"},
    "rank_caught": {"en": "Top-{k} ARG, also top-{k} composite", "pt": "Top {k} ARG, também top {k} composto"},
    "rank_other": {"en": "Other sites", "pt": "Outros locais"},
    "why_lbl": {"en": "Why: the correlations behind it", "pt": "Porquê: as correlações por trás"},
    "plan_know": {"en": "What would change each verdict", "pt": "O que mudaria cada veredicto"},
    # ---- about
    "about_title": {"en": "About AquaSentinel", "pt": "Sobre o AquaSentinel"},
    "about_body": {
        "en": "AquaSentinel is a prototype built for the OneAquaHealth IEEE Global Hackathon. It "
              "turns citizen and environmental stream data into insights that have been tested "
              "before they are shown: each one is challenged for city confounding, for multiple "
              "testing or against a simulated null, and labelled supported, exploratory or rejected.\n\n"
              "**Track:** Data-to-Insight. It also addresses AI-Supported Assessment (explainable "
              "checks on citizen data) and Digital Health Standards (the `api/` folder serves the "
              "same data as OGC SensorThings-shaped JSON, GeoJSON and an HL7 FHIR Observation mapping).\n\n"
              "Data: the public OneAquaHealth Resilience Map API. The interface is in English and "
              "Portuguese; the insight texts are generated in English.",
        "pt": "O AquaSentinel é um protótipo criado para o OneAquaHealth IEEE Global Hackathon. "
              "Transforma dados de ribeiras, de cidadãos e ambientais, em descobertas testadas antes "
              "de serem mostradas: cada uma é posta à prova quanto ao efeito da cidade, a testes "
              "múltiplos ou contra uma simulação nula, e classificada como sustentada, exploratória "
              "ou rejeitada.\n\n"
              "**Categoria:** Data-to-Insight. Responde também a AI-Supported Assessment (verificações "
              "explicáveis dos dados dos cidadãos) e Digital Health Standards (a pasta `api/` serve os "
              "mesmos dados em JSON no formato OGC SensorThings, GeoJSON e HL7 FHIR Observation).\n\n"
              "Dados: API pública do OneAquaHealth Resilience Map. A interface está em inglês e "
              "português; os textos das descobertas são gerados em inglês.",
    },
    "honesty_banner": {
        "en": "The data is a snapshot: one lab sample per site, each city sampled in a single "
              "campaign between May and September 2023. AquaSentinel therefore describes and "
              "prioritises; it does not forecast.",
        "pt": "Os dados são um instantâneo: uma amostra de laboratório por local, cada cidade "
              "amostrada numa única campanha entre maio e setembro de 2023. Por isso o "
              "AquaSentinel descreve e prioriza; não faz previsões.",
    },
    "data_dictionary": {"en": "Data dictionary", "pt": "Dicionário de dados"},
    "download_insights": {"en": "Download all insights with their evidence (JSON)",
                          "pt": "Descarregar todas as descobertas com a evidência (JSON)"},
}


def t(key: str, lang: str = "en") -> str:
    entry = _STR.get(key)
    if not entry:
        return key
    return entry.get(lang) or entry.get("en") or key
